
api:
  container_name: ecommerce
  image: secret06/nodejs:2.1
  command : nodemon app.js
  restart: always
  ports:
    - "8085:8085"
  volumes:
    - .:/app
  links:
      - mongodbs

mongodbs:
  container_name: mongodbs
  restart: always
  volumes:
    - ./db:/data/db
  image: mongo:3.2
  ports:
    - "27017:27017"
